### ISSUE TITLE
Conan Studio Equipment card text area enhancements

### ISSUE THREAD

**Issue by SmallRealities** [rafdulaf/companion4monolith#139]
- Ability to zoom text area on equipment cards
- Wrap text around encumbrance icon
- Ability raise/lower text separator

**Comment by rafdulaf** [comment]
Thanks for this return

> Ability to zoom text area on equipment cards
Yes I can do it the same way I did for spell cards

> Wrap text around encumbrance icon
Not sure I can technically automize this, but I will try. What I dit in Conqueror cards for the moment is tu use non-breaking space like this one " " at the end of sentences

> Ability raise/lower text separator
What you call "text separator" is the black line above text?
I did it this way because in conqueror all cards have the line at the exact same location, but I can add this indeed.

**Comment by rafdulaf** [comment]
Will be delivered in the next version
